language: python
sudo: false

env:
   global:
      - image=pythonnode_slave

matrix:
  include:
    - python: 2.7
      env: TRAVIS_NODE_VERSION="4"
    - python: 2.7
      env: TRAVIS_NODE_VERSION="6"
    - python: 3.5
      env: TRAVIS_NODE_VERSION="6"
    - python: 3.6
      env: TRAVIS_NODE_VERSION="6"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - pip install -U pip
  - "pip install --no-binary=:all: buildbot" # need --no-binary=:all: to get the test framework
  - pip install -r example/requirements.txt
  - pip install -e .
  - pip install mock

script:
  - python setup.py develop
  - trial buildbot_travis.tests

after_failure: "cat _trial_temp/test.log"
