env:
   global:
      - image=pythonnode_slave
language: python
python:
  - "2.7"

install:
  - pip install -r example/requirements.txt
  - pip install --pre buildbot_pkg
  - pip install --pre buildbot-slave==0.9.0b7
  - pip install -e .
  - pip install mock

script: trial buildbot_travis/tests 
after_failure: "cat _trial_temp/test.log"


